services:
  web:
    build: .
    container_name: lamolienda_web
    ports:
      - "8082:80"
    volumes:
      - data:/var/www/html/data
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped

volumes:
  data:
